/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package breaker;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAPaddle() {
        App classUnderTest = new App();
        assertNotNull("No player paddle", classUnderTest.player);
    }
}
